### ISSUE TITLE
5.0 container doesn't start

### ISSUE THREAD

**Issue by HariSekhon** [docker-library/elasticsearch#105] opened 2016-06-03 12:32 UTC
```
docker run -ti elasticsearch:5.0
[2016-06-03 12:04:46,733][INFO ][node                     ] [Dakota North] version[5.0.0-alpha2], pid[1], build[e3126df/2016-04-26T12:08:58.960Z]
[2016-06-03 12:04:46,735][INFO ][node                     ] [Dakota North] initializing ...
[2016-06-03 12:04:47,464][INFO ][plugins                  ] [Dakota North] modules [lang-mustache, lang-painless, ingest-grok, reindex, lang-expression, lang-groovy], plugins []
[2016-06-03 12:04:47,501][INFO ][env                      ] [Dakota North] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [33gb], net total_space [95gb], spins? [possibly], types [ext4]
[2016-06-03 12:04:47,502][INFO ][env                      ] [Dakota North] heap size [990.7mb], compressed ordinary object pointers [true]
[2016-06-03 12:04:51,565][INFO ][node                     ] [Dakota North] initialized
[2016-06-03 12:04:51,566][INFO ][node                     ] [Dakota North] starting ...
[2016-06-03 12:04:51,765][INFO ][transport                ] [Dakota North] publish_address {172.17.0.3:9300}, bound_addresses {[::]:9300}
Exception in thread "main" java.lang.RuntimeException: bootstrap checks failed
initial heap size [268435456] not equal to maximum heap size [1073741824]; this can cause resize pauses and prevents mlockall from locking the entire heap
max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:93)
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:66)
        at org.elasticsearch.bootstrap.Bootstrap$5.validateNodeBeforeAcceptingRequests(Bootstrap.java:191)
        at org.elasticsearch.node.Node.start(Node.java:323)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:206)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:269)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
Refer to the log for complete error details.
[2016-06-03 12:04:51,788][INFO ][node                     ] [Dakota North] stopping ...
[2016-06-03 12:04:51,894][INFO ][node                     ] [Dakota North] stopped
[2016-06-03 12:04:51,896][INFO ][node                     ] [Dakota North] closing ...
[2016-06-03 12:04:51,948][INFO ][node                     ] [Dakota North] closed
```

**Comment by yosifkit** [comment] 2016-06-03 17:55
`5.0` is an alpha release, which is why latest is still `2.3`. Duplicate of #98.

**Closed by yosifkit** 2016-06-03 17:55 UTC

**Comment by ip2k** [comment] 2016-08-19 02:27
@HariSekhon add `-e ES_JAVA_OPTS="-Xms1g -Xmx1g"` and it should work. See http://stackoverflow.com/questions/14763079/what-are-the-xms-and-xmx-parameters-when-starting-jvms and https://github.com/elastic/elasticsearch/issues/17974 for an explanation.
