### ISSUE TITLE
Acces denied to mounted volume config

### ISSUE THREAD

**Issue by easyrasta** [docker-library/elasticsearch#75] opened 2015-12-10 17:18 UTC
If I un docker image with -v option for config eg: -v "$PWD/config":/usr/share/elasticsearch/config I got:
```
Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
...
```

**Comment by yosifkit** [comment] 2016-01-11 18:18
duplicate of #74

**Closed by yosifkit** 2016-01-11 18:18 UTC
