### ISSUE TITLE
CircleCI : can't start ES 2.0

### ISSUE THREAD

**Issue by nlamirault** [docker-library/elasticsearch#67] opened 2015-11-03 09:51 UTC
hi
i would like to launch ES 2.0 on a CircleCI build, i"ve got this error : 

```bash
ubuntu@box684:~$ docker run --name elasticsearch  -it --rm=true elasticsearch:2.0 --network.host=_non_loopback_
Unable to find image 'elasticsearch:2.0' locally
2.0: Pulling from library/elasticsearch
575489a51992: Pull complete 
6845b83c79fb: Pull complete 
f9fffdafe16d: Pull complete 
06059b5e7950: Pull complete 
efbfbb2501e1: Pull complete 
be2d5fd45a31: Pull complete 
598179ea500b: Pull complete 
391eba5e09bd: Pull complete 
28e1cdf46191: Pull complete 
502293e1b7a6: Pull complete 
e8c260e35308: Pull complete 
67720b0c8716: Pull complete 
31152391da21: Pull complete 
fff711d06832: Pull complete 
45c9593e1dfb: Pull complete 
69276da6d2ee: Pull complete 
ec07ee46a006: Pull complete 
f440e8cb0417: Pull complete 
7c3969cf1c4d: Pull complete 
d5a7624cb70c: Pull complete 
66fa90dca619: Pull complete 
3b9ff4307668: Pull complete 
e66c7a2d67f7: Pull complete 
db53c59953a7: Pull complete 
9288178fb5db: Pull complete 
6a815676799e: Pull complete 
ec1ba95674b4: Pull complete 
79438b7c8046: Pull complete 
library/elasticsearch:2.0: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:9247276d14203fcc5225627d546499d39cae273d5df3e2a068ff0e3866c230c7
Status: Downloaded newer image for elasticsearch:2.0
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
[2015-11-03 09:49:20,109][INFO ][node                     ] [Liz Allan] version[2.0.0], pid[1], build[de54438/2015-10-22T08:09:48Z]
[2015-11-03 09:49:20,122][INFO ][node                     ] [Liz Allan] initializing ...
[2015-11-03 09:49:20,254][INFO ][plugins                  ] [Liz Allan] loaded [], sites []
[2015-11-03 09:49:20,520][INFO ][env                      ] [Liz Allan] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/xvdh)]], net usable_space [173.6gb], net tota
l_space [239.9gb], spins? [possibly], types [btrfs]
[2015-11-03 09:49:26,441][INFO ][node                     ] [Liz Allan] initialized
[2015-11-03 09:49:26,441][INFO ][node                     ] [Liz Allan] starting ...
Exception in thread "main" BindTransportException[Failed to bind to [9300-9400]]; nested: ChannelException[Failed to bind to: /fe80:0:0:0:42:acff:fe11:b%eth0:9400]; nested: BindExcepti
on[Cannot assign requested address];
Likely root cause: java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Refer to the log for complete error details.
[2015-11-03 09:49:26,810][INFO ][node                     ] [Liz Allan] stopping ...
[2015-11-03 09:49:26,820][INFO ][node                     ] [Liz Allan] stopped
[2015-11-03 09:49:26,820][INFO ][node                     ] [Liz Allan] closing ...
[2015-11-03 09:49:26,833][INFO ][node                     ] [Liz Allan] closed
Error deleting container: Error response from daemon: Cannot destroy container 7ec4735cd0b0fe5ea8dfc524e5c602dbe95c87bdc20147af122312eda3b1bf63: Driver btrfs failed to remove root file
system 7ec4735cd0b0fe5ea8dfc524e5c602dbe95c87bdc20147af122312eda3b1bf63: Failed to destroy btrfs snapshot: operation not permitted
```

any idea to fix that ?
Thanks

**Comment by tianon** [comment] 2015-11-16 17:20
Thanks for the report -- this is a duplicate of #52. :+1:  (Closing so we can track it in one place.)

**Closed by tianon** 2015-11-16 17:20 UTC
